SELECT * FROM EMP
WHERE SAL LIKE '____.00';

SELECT * FROM EMP
WHERE ENAME LIKE 'S____'

SELECT CONCAT(ENAME, ' is ' ,JOB) AS INTRO from EMP;
SELECT SUBSTRING(ENAME, 1, 3) from EMP;
SELECT LEN(ENAME) from EMP;
SELECT ENAME, CHARINDEX('S', ENAME) from EMP;
SELECT REPLACE(ENAME, 'S', '*') from EMP;
SELECT ROUND(124.6555555555, 5, 0);
SELECT ABS(-850);
SELECT GETDATE();
SELECT DATENAME(YEAR, GETDATE()) AS 'Year';
SELECT DATENAME(QUARTER, GETDATE()) AS 'Quarter';
SELECT DATENAME(MONTH, GETDATE()) AS 'Month Name';
SELECT DATENAME(DAYOFYEAR, GETDATE()) AS 'DayOfYear';
SELECT DATENAME(DAY, GETDATE()) AS 'Day';
SELECT DATENAME(WEEK, GETDATE()) AS 'Week';
SELECT DATENAME(WEEKDAY, GETDATE()) AS 'Day of the Week';
SELECT DATENAME(HOUR, GETDATE()) AS 'Hour';
SELECT DATENAME(MINUTE, GETDATE()) AS 'Minute';
SELECT DATENAME(SECOND, GETDATE()) AS 'Second';
SELECT DATEPART(YYYY, GETDATE());
SELECT DATEPART(mm, GETDATE());
SELECT DATEPART(dd, GETDATE());

Select ENAME,JOB from EMP;
Select CONVERT(varchar(30), HIRDATE, 101) AS 'HIRE DATE' FROM EMP;
Select CONCAT( DATEPART(mm, HIRDATE),'-', DATEPART(dd, HIRDATE), '-', DATEPART(yyyy, HIRDATE) ) from EMP;
SELECT LOWER(ENAME) AS lower_case from EMP;

DROP VIEW IF EXISTS EMP_NAME;

CREATE VIEW EMP_NAME AS
SELECT ENAME, JOB, HIRDATE
FROM dbo.EMP;
SELECT *FROM EMP;
SELECT *FROM EMP_NAME;
/*Lab Tasks 1,2,3*/
/*Task 1*/
Select *
from EMP, DEPT
where sal > 2000 AND dname = 'RESEARCH';
/*Task 2*/ 
SELECT MAX(SAL) AS MaximumSalary,MIN(SAL) AS MinimumSalary from dbo.EMP where DEPTINO = 20;
/*Task 3*/
SELECT empno, ename
from EMP   
where EMP.DEPTINO > 10 AND ename LIKE '%s%';
/*Task 4*/
SELECT *
FROM EMP
WHERE SAL > (SELECT TOP 1 SAL FROM EMP WHERE EMP.ENAME = 'JONES');


SELECT ENAME, JOB, DNAME FROM dbo.EMP INNER JOIN dbo.DEPT ON dbo.EMP.DEPTINO =
dbo.DEPT.DEPTNO;

SELECT* FROM EMP
SELECT* FROM DEPT