

CREATE TABLE User2
(
	ID int CONSTRAINT not_null_constraint NOT NULL PRIMARY KEY CHECK(ID < 600),
	NAME VARCHAR(30) CONSTRAINT not_null_NAME NOT NULL,
	USERNAME VARCHAR(30) CONSTRAINT not_null_NAME NOT NULL,
	DOB date
);
INSERT INTO User2 VALUES
( 11, 'Ahmed' , 'Baig' , CONVERT(date,'17-MAY-2001') );
INSERT INTO User2 VALUES
( 23, 'Hasnat' , 'Rasool' , CONVERT(date,'20-JAN-2001') );
INSERT INTO User2 VALUES
( 41, 'Humaid' , 'Ashraf' , CONVERT(date,'25-DEC-2001') );

UPDATE User2
SET name = 'Naufil Moten'
WHERE ID = 10;

DELETE FROM User2
WHERE ID = 30;


CREATE TABLE Post2(
	ID int CONSTRAINT not_null_constraint NOT NULL PRIMARY KEY CHECK(ID < 600),
	DESCRIPTION VARCHAR(30) CONSTRAINT not_null_NAME NOT NULL,
	DATE date,
	USERID int CONSTRAINT FORK FOREIGN KEY(USERID) REFERENCES User2 (ID)
	ON DELETE CASCADE
);


INSERT INTO Post2 VALUES
( 1, 'working at a farm' , CONVERT(date,'20-DEC-2002'),10 );
INSERT INTO Post2 VALUES
( 2, 'working at abroad' , CONVERT(date,'20-DEC-2002'),20 );
INSERT INTO Post2 VALUES
( 3, 'working at a shop' , CONVERT(date,'20-DEC-2002'),30 );


CREATE TABLE COMMENT1(
	ID int CONSTRAINT not_null_constraint NOT NULL PRIMARY KEY CHECK(ID < 600),
	DESCRIPTION VARCHAR(30) CONSTRAINT not_null_NAME NOT NULL,
	DATE date,
	USERID int CONSTRAINT FORK1 FOREIGN KEY(USERID) REFERENCES User2 (ID),
	POSTID int CONSTRAINT FORK2 FOREIGN KEY(POSTID) REFERENCES Post2 (ID)
);

INSERT INTO COMMENT1 VALUES
( 10, 'very good worker' , CONVERT(date,'20-DEC-2002'),10,1 );
INSERT INTO COMMENT1 VALUES
( 11, 'good at job' , CONVERT(date,'20-DEC-2002'),20,2 );
INSERT INTO COMMENT1 VALUES
( 12, 'not really good' , CONVERT(date,'30-DEC-2002'),30,3 );


DELETE FROM Comment1
WHERE ID = 12;

SELECT* FROM User2
SELECT * FROM Post2
SELECT * FROM COMMENT1